version: "3.1"

services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./wptheme/:/var/www/html/wp-content/themes/wptheme
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./.wpfiles:/var/www/html/
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.db_data/:/var/lib/mysql
